baseURL = 'https://helenqu.com/blog/'
languageCode = 'en-us'
title = 'helen qu'
theme = 'shibui'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[params]
  math = false
  customCSS = ["math.css"]
  author = "Helen Qu"
  author_url = "https://helenqu.com"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services]
  [services.googleAnalytics]
    id = 'G-TTK0ES3QC3'